const SHEET_NAME = '';
const PRODUCT_NAMES = ['老鼠肉','里肌肉','梅花肉','豬腳','三層肉','排骨'];
function getOrderSheet_(){const ss=SpreadsheetApp.getActiveSpreadsheet();return SHEET_NAME?ss.getSheetByName(SHEET_NAME):ss.getSheets()[0];}
function ensureStatusColumns_(sheet){['訂單狀態','付款狀態','出貨狀態'].forEach(h=>{const headers=sheet.getRange(1,1,1,Math.max(sheet.getLastColumn(),1)).getDisplayValues()[0];if(headers.indexOf(h)===-1)sheet.getRange(1,sheet.getLastColumn()+1).setValue(h);});}
function doPost(e){try{const sheet=getOrderSheet_(),data=JSON.parse(e.postData.contents||'{}');if(sheet.getLastRow()===0)sheet.appendRow(['訂單編號','建立時間','訂購人姓名','聯絡電話','配送方式','收件人姓名','收件地址','商品明細','總包數','商品金額','運費','應付總額','匯款後五碼','備註','訂單狀態','付款狀態','出貨狀態']);else ensureStatusColumns_(sheet);const now=new Date(),orderNumber=data.orderNumber||('QR'+Utilities.formatDate(now,'Asia/Taipei','yyyyMMddHHmmss'));sheet.appendRow([orderNumber,Utilities.formatDate(now,'Asia/Taipei','yyyy/MM/dd HH:mm:ss'),data.buyerName||'',data.phone||'',data.shippingMethod||'',data.receiverName||'',data.address||'',data.items||'',Number(data.totalQty||0),Number(data.goodsAmount||0),Number(data.shippingFee||0),Number(data.totalAmount||0),data.last5||'',data.note||'','已收到訂單','待確認','尚未出貨']);return ContentService.createTextOutput(JSON.stringify({success:true,orderNumber})).setMimeType(ContentService.MimeType.JSON)}catch(error){return ContentService.createTextOutput(JSON.stringify({success:false,message:error.message})).setMimeType(ContentService.MimeType.JSON)}}
function doGet(e){try{const a=String(e.parameter.action||'');if(a==='queryOrder')return handleOrderQuery_(e);if(a==='hotSales')return handleHotSales_(e);return jsonpOutput_({success:false,message:'Unsupported action'},e.parameter.callback)}catch(error){return jsonpOutput_({success:false,message:error.message},e.parameter.callback)}}
function handleOrderQuery_(e){const sheet=getOrderSheet_();ensureStatusColumns_(sheet);const n=String(e.parameter.orderNumber||'').trim().toUpperCase(),l=String(e.parameter.last5||'').trim(),v=sheet.getDataRange().getDisplayValues();if(!/^QR\d{14}$/.test(n)||!/^\d{5}$/.test(l))return jsonpOutput_({success:false,message:'查詢資料格式不正確'},e.parameter.callback);if(v.length<2)return jsonpOutput_({success:false,message:'查無符合資料'},e.parameter.callback);const H={};v[0].forEach((x,i)=>H[x]=i);for(let r=v.length-1;r>=1;r--){if(String(v[r][H['訂單編號']]||'').trim().toUpperCase()===n&&String(v[r][H['匯款後五碼']]||'').trim()===l)return jsonpOutput_({success:true,order:{orderNumber:n,items:v[r][H['商品明細']]||'',totalAmount:Number(String(v[r][H['應付總額']]||'0').replace(/[^\d.-]/g,''))||0,shippingMethod:v[r][H['配送方式']]||'',orderStatus:v[r][H['訂單狀態']]||'已收到訂單',paymentStatus:v[r][H['付款狀態']]||'待確認',shippingStatus:v[r][H['出貨狀態']]||'尚未出貨'}},e.parameter.callback)}return jsonpOutput_({success:false,message:'查無符合資料，請確認訂單編號與匯款後五碼。'},e.parameter.callback)}
function handleHotSales_(e){const s=getOrderSheet_(),v=s.getDataRange().getDisplayValues();if(v.length<2)return jsonpOutput_({success:true,rankings:PRODUCT_NAMES.map(name=>({name,qty:0}))},e.parameter.callback);const idx=v[0].indexOf('商品明細');if(idx===-1)throw new Error('找不到「商品明細」欄位');const t={};PRODUCT_NAMES.forEach(n=>t[n]=0);for(let r=1;r<v.length;r++){const text=String(v[r][idx]||'');PRODUCT_NAMES.forEach(n=>{const re=new RegExp(n+'\\s*[×xX＊*]\\s*(\\d+)\\s*(?:包)?','g');let m;while((m=re.exec(text))!==null)t[n]+=Number(m[1]||0)})}const rankings=PRODUCT_NAMES.map((name,order)=>({name,qty:t[name],order})).sort((a,b)=>b.qty!==a.qty?b.qty-a.qty:a.order-b.order).map(({name,qty})=>({name,qty}));return jsonpOutput_({success:true,rankings},e.parameter.callback)}
function jsonpOutput_(data,callback){const json=JSON.stringify(data),safe=String(callback||'').replace(/[^\w.$]/g,'');return ContentService.createTextOutput(safe?safe+'('+json+');':json).setMimeType(safe?ContentService.MimeType.JAVASCRIPT:ContentService.MimeType.JSON)}
